name: pubdev-publish
on:
  # https://docs.github.com/cn/actions/using-workflows/events-that-trigger-workflows#release
  release:
    types: [published]
jobs:
  publishing:
    runs-on: ubuntu-latest
    steps:
      - name: 'checkout'
        uses: actions/checkout@v2   # required!
      - name: 'publish to pub.dev'
        uses: k-paxian/dart-package-publisher@master
        with:
          accessToken: ${{ secrets.PUBDEV_ACCESS_TOKEN }}
          refreshToken: ${{ secrets.PUBDEV_REFRESH_TOKEN }}
          # skipTests: true  # 临时
          force: true
          flutter: true